name: Java CI with Gradle and SonarQube Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Required for SonarQube analysis

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Make Gradle Wrapper executable
    - name: Make Gradle Wrapper executable
      run: chmod +x gradlew

    # Step 4: Build the project
    - name: Build with Gradle
      run: ./gradlew build

    # Step 5: Set up SonarQube Scanner
    - name: Set up SonarQube Scanner
      uses: SonarSource/sonarqube-scan-action@v1
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        sonar-host-url: ${{ secrets.SONAR_HOST_URL }}

    # Step 6: Run SonarQube analysis
    - name: Run SonarQube analysis
      run: ./gradlew sonar
